#!/bin/bash

if [ $# -ne 2 ]; then
	echo "usage: $0 source dist [first step]"
	exit 1
fi

mkdir $2
find cavity -maxdepth 1 | grep -vx cavity | grep -v [0-9] | xargs cp -r -t $2

if [ $# -ne 3 ]; then
	cp -r $1/0 $2/
else
	cp -r $1/$3 $2/
fi
